// Tailwind build for the utility classes the markup still uses (v3.4.17, the
// version of the former browser runtime). Regenerate after changing markup:
//   bash .github/scripts/build-utilities-css.sh
// Class names that the scripts assemble at runtime (for example
// bg-${color}-100) cannot be found by scanning, so they are listed below.
module.exports = {
    darkMode: 'class',
    content: ['./frontend/*.html', './frontend/*.js'],
    theme: { extend: {} },
    safelist: [
        'bg-gray-100',
        'bg-gray-50',
        'bg-green-100',
        'bg-green-50',
        'bg-orange-100',
        'bg-orange-50',
        'bg-red-100',
        'bg-red-50',
        'bg-yellow-100',
        'bg-yellow-50',
        'border-gray-100',
        'border-gray-300',
        'border-green-100',
        'border-green-300',
        'border-orange-100',
        'border-orange-300',
        'border-red-100',
        'border-red-300',
        'border-yellow-100',
        'border-yellow-300',
        'dark:bg-gray-900/10',
        'dark:bg-gray-900/30',
        'dark:bg-green-900/10',
        'dark:bg-green-900/30',
        'dark:bg-orange-900/10',
        'dark:bg-orange-900/30',
        'dark:bg-red-900/10',
        'dark:bg-red-900/30',
        'dark:bg-yellow-900/10',
        'dark:bg-yellow-900/30',
        'dark:border-gray-700',
        'dark:border-gray-900/30',
        'dark:border-green-700',
        'dark:border-green-900/30',
        'dark:border-orange-700',
        'dark:border-orange-900/30',
        'dark:border-red-700',
        'dark:border-red-900/30',
        'dark:border-yellow-700',
        'dark:border-yellow-900/30',
        'dark:hover:bg-gray-900/20',
        'dark:hover:bg-green-900/20',
        'dark:hover:bg-orange-900/20',
        'dark:hover:bg-red-900/20',
        'dark:hover:bg-yellow-900/20',
        'dark:text-gray-300',
        'dark:text-gray-400',
        'dark:text-green-300',
        'dark:text-green-400',
        'dark:text-orange-300',
        'dark:text-orange-400',
        'dark:text-red-300',
        'dark:text-red-400',
        'dark:text-yellow-300',
        'dark:text-yellow-400',
        'hover:bg-gray-100',
        'hover:bg-green-100',
        'hover:bg-orange-100',
        'hover:bg-red-100',
        'hover:bg-yellow-100',
        'hover:text-gray-600',
        'hover:text-green-600',
        'hover:text-orange-600',
        'hover:text-red-600',
        'hover:text-yellow-600',
        'text-gray-400',
        'text-gray-600',
        'text-gray-700',
        'text-green-400',
        'text-green-600',
        'text-green-700',
        'text-orange-400',
        'text-orange-600',
        'text-orange-700',
        'text-red-400',
        'text-red-600',
        'text-red-700',
        'text-yellow-400',
        'text-yellow-600',
        'text-yellow-700',
    ],
};
